### ISSUE TITLE
We need an Effect Picture

### ISSUE THREAD

**Issue by CNMathon** [Madchatthew/flarum-ext-themelightshadow#15]
I think that if you put an effect picture for it, we will know more about what kind of project it is.

**Comment by Madchatthew** [comment]
I am not sure what you mean by effect picture.

**Comment by daxpandhi** [comment]
I think he means a screenshot.

**Comment by Madchatthew** [comment]
It looks like the screenshots will have to be redone,, both here and on the post in the discussion forums.

**Comment by Madchatthew** [comment]
I added screenshots, updated/fixed some styles and created a new release. Thank you for your input.
